#!/usr/bin/env python3
"""Stage the AgentShield agent for Amazon Bedrock AgentCore Runtime (CodeZip build).

Copies the `agent` package into build/runtime/, writes the runtime entrypoint and dependencies,
and renders agentcore/agentcore.json + aws-targets.json from the template and .env.
Usage: python scripts/stage_agentcore.py && cd agentcore && agentcore deploy -y
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNTIME = ROOT / "build" / "runtime"

# Forwarded to the runtime. Secrets stay out of git: they are read from .env at stage time.
RUNTIME_ENV = [
    "AWS_REGION",
    "BEDROCK_MODEL_ID",
    "GATE2_MODEL_ID",
    "BASE_RPC_URL",
    "BASE_SEPOLIA_RPC_URL",
    "REPUTATION_REGISTRY_ADDRESS",
    "CLICKHOUSE_URL",
    "CLICKHOUSE_USER",
    "CLICKHOUSE_PASSWORD",
    "CLICKHOUSE_DATABASE",
]

MAIN_PY = '''"""AgentCore Runtime entrypoint (generated by scripts/stage_agentcore.py)."""
from agent.agentcore_app import app

if __name__ == "__main__":
    app.run()
'''

PYPROJECT = """[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agentshield-runtime"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = [
    "bedrock-agentcore >= 1.9.1",
    "aws-opentelemetry-distro ~= 0.18.0",
    "botocore[crt] >= 1.35.0",
    "strands-agents >= 1.55.0",
    "pydantic >= 2.0.0",
    "httpx >= 0.27.0",
    "eth-abi >= 5.0.0",
    "eth-utils >= 4.0.0",
    "clickhouse-connect >= 0.8.0",
    "python-dotenv >= 1.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
"""

BEDROCK_POLICY = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream", "bedrock:Converse", "bedrock:ConverseStream"],
            "Resource": ["arn:aws:bedrock:*::foundation-model/*", "arn:aws:bedrock:*:*:inference-profile/*"],
        }
    ],
}


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    path = ROOT / ".env"
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip()
    return {**env, **{k: v for k, v in os.environ.items() if k in RUNTIME_ENV or k == "AWS_ACCOUNT_ID"}}


def main() -> None:
    env = load_env()
    if RUNTIME.exists():
        shutil.rmtree(RUNTIME)
    shutil.copytree(ROOT / "agent", RUNTIME / "agent", ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "server.py", "cli.py"))
    (RUNTIME / "main.py").write_text(MAIN_PY)
    (RUNTIME / "pyproject.toml").write_text(PYPROJECT)
    (RUNTIME / "bedrock-invoke-policy.json").write_text(json.dumps(BEDROCK_POLICY, indent=2))

    config = json.loads((ROOT / "agentcore" / "agentcore.template.json").read_text())
    config["runtimes"][0]["envVars"] = [{"name": k, "value": env[k]} for k in RUNTIME_ENV if env.get(k)]
    (ROOT / "agentcore" / "agentcore.json").write_text(json.dumps(config, indent=2))

    account = env.get("AWS_ACCOUNT_ID")
    if not account:
        try:
            import boto3

            account = boto3.client("sts").get_caller_identity()["Account"]
        except Exception as exc:
            raise SystemExit(f"Set AWS credentials or AWS_ACCOUNT_ID in .env ({exc})")
    targets = [{"name": "default", "description": "AgentShield demo", "account": account, "region": env.get("AWS_REGION", "us-west-2")}]
    (ROOT / "agentcore" / "aws-targets.json").write_text(json.dumps(targets, indent=2))
    forwarded = ", ".join(v["name"] for v in config["runtimes"][0]["envVars"])
    print(f"Staged {RUNTIME.relative_to(ROOT)} for account {account}; env: {forwarded}")


if __name__ == "__main__":
    main()
